SensorData/Models/Frequency.cs
using System.ComponentModel;

namespace SensorData.Models
{
    public class Frequency
    {
        public int Id { get; set; }

        [DisplayName("Sensor")]
        public int Sensor_Id { get; set; }

        [DisplayName("SS: 0 - 20")]
        public float Frl1 { get; set;}

        [DisplayName("SS: 20 - 40")]
        public float Frl2 { get; set;}
        [DisplayName("SS: 40 - 60")]
        public float Frl3 { get; set;}

        [DisplayName("Hora")]
        public DateTime ReadDateTime { get; set;} = DateTime.Now.ToLocalTime();

    }
}

SensorData/Controllers/Frequencies1Controller.cs
/// <summary>
/// 
/// This code is to manipulate the Frequencies model from Bananas End Device to be presented as moisture on Views
/// 
/// Author: Alexandre Cavalcanti
/// Date: 05/31/2023
/// 
/// </summary>

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SensorData.Models;

namespace SensorData.Controllers
{
    public class Frequencies1Controller : Controller
    {
        private readonly SensorContext _context;

        public Frequencies1Controller(SensorContext context)
        {
            _context = context;
        }

        // GET: Frequencies1
        public async Task<IActionResult> Index()
        {

            return View(await FrequenciesList());

        }

        //GET: Frequencies/ViewTable

        public async Task<IActionResult> ViewTable()
        {

            var frequencies = await FrequenciesList();


            return View(frequencies);
        }


        // GET: Frequencies1/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Frequencies == null)
            {
                return NotFound();
            }

            var frequency = await _context.Frequencies
                .FirstOrDefaultAsync(m => m.Id == id);
            if (frequency == null)
            {
                return NotFound();
            }

            return View(frequency);
        }

        // GET: Frequencies1/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Frequencies1/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Sensor_Id,Frl1,Frl2,Frl3,ReadDateTime")] Frequency frequency)
        {
            if (ModelState.IsValid)
            {
                _context.Add(frequency);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(frequency);
        }

        // GET: Frequencies1/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Frequencies == null)
            {
                return NotFound();
            }

            var frequency = await _context.Frequencies.FindAsync(id);
            if (frequency == null)
            {
                return NotFound();
            }
            return View(frequency);
        }

        // POST: Frequencies1/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Sensor_Id,Frl1,Frl2,Frl3,ReadDateTime")] Frequency frequency)
        {
            if (id != frequency.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(frequency);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FrequencyExists(frequency.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(frequency);
        }

        // GET: Frequencies1/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Frequencies == null)
            {
                return NotFound();
            }

            var frequency = await _context.Frequencies
                .FirstOrDefaultAsync(m => m.Id == id);
            if (frequency == null)
            {
                return NotFound();
            }

            return View(frequency);
        }

        // POST: Frequencies1/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Frequencies == null)
            {
                return Problem("Entity set 'SensorContext.Frequencies'  is null.");
            }
            var frequency = await _context.Frequencies.FindAsync(id);
            if (frequency != null)
            {
                _context.Frequencies.Remove(frequency);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool FrequencyExists(int id)
        {
          return (_context.Frequencies?.Any(e => e.Id == id)).GetValueOrDefault();
        }

        private async Task<List<Frequency>> FrequenciesList()
        {

            if (_context.Frequencies == null)
            {
                return null;
            }
            if (_context.Spots == null)
            {
                return null;
            }
            var spot = await _context.Spots.ToListAsync();      //Para ser usado na conversão de Frel para Umid%
            var frequency = await _context.Frequencies
                .ToListAsync();

            if (frequency == null)
            {
                return null;
            }
            if (spot == null)
            {
                return null;
            }
            ///<summary>
            ///
            /// Convert frequencies into percent of soil moisture
            /// 
            /// </summary>
            foreach (Frequency item in frequency)
            {

                foreach (Spot sitem in spot.Where(s => s.Sensor_Id == item.Sensor_Id).Where(t => t.Name == "Frl3"))
                {
                    item.Frl3 = (item.Frl3 * sitem.A) + sitem.B;
                }

                foreach (Spot sitem in spot.Where(s => s.Sensor_Id == item.Sensor_Id).Where(t => t.Name == "Frl2"))
                {
                    item.Frl2 = (item.Frl2 * sitem.A) + sitem.B;
                }

                foreach (Spot sitem in spot.Where(s => s.Sensor_Id == item.Sensor_Id).Where(t => t.Name == "Frl1"))
                {
                    item.Frl1 = (item.Frl1 * sitem.A) + sitem.B;
                }


            }

            return frequency;


        }

    }
}

SensorData/Controllers/FrequenciesController.cs
/// <summary>
/// 
/// This code is to manipulate the Frequencies model from SS End Device to be presented as moisture on Views
/// 
/// Author: Alexandre Cavalcanti
/// Date: 05/31/2023
/// 
/// </summary>

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using NuGet.Protocol;
using SensorData.Models;


namespace SensorData.Controllers
{
    public class FrequenciesController : Controller
    {
        private readonly SensorContext _context;

        public FrequenciesController(SensorContext context)
        {
            _context = context;
        }

        // GET: Frequencies
        public async Task<IActionResult> Index()
        {
            return View(await FrequenciesList());
        }

        //GET: Frequencies/ViewTable

        public async Task<IActionResult> ViewTable()
        {

            var frequencies = await FrequenciesList();


            return View(frequencies);
        }


        // GET: Frequencies/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Frequencies == null)
            {
                return NotFound();
            }

            var frequency = await _context.Frequencies
                .FirstOrDefaultAsync(m => m.Id == id);
            if (frequency == null)
            {
                return NotFound();
            }

            return View(frequency);
        }

        // GET: Frequencies/Create
        public IActionResult Create()
        {
            return View();
        }

        //POST: Frequencies/Create
        //To protect from overposting attacks, enable the specific properties you want to bind to.
        //For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Sensor_Id,Frl1,Frl2,Frl3,ReadDateTime")] Frequency frequency)
        {
            if (ModelState.IsValid)
            {
                _context.Add(frequency);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(frequency);
        }


        // GET: Frequencies/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Frequencies == null)
            {
                return NotFound();
            }

            var frequency = await _context.Frequencies.FindAsync(id);
            if (frequency == null)
            {
                return NotFound();
            }
            return View(frequency);
        }

        // POST: Frequencies/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Sensor_Id,Frl1,Frl2,Frl3,ReadDateTime")] Frequency frequency)
        {
            if (id != frequency.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(frequency);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FrequencyExists(frequency.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(frequency);
        }

        // GET: Frequencies/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Frequencies == null)
            {
                return NotFound();
            }

            var frequency = await _context.Frequencies
                .FirstOrDefaultAsync(m => m.Id == id);
            if (frequency == null)
            {
                return NotFound();
            }

            return View(frequency);
        }

        // POST: Frequencies/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Frequencies == null)
            {
                return Problem("Entity set 'SensorContext.Frequencies'  is null.");
            }
            var frequency = await _context.Frequencies.FindAsync(id);
            if (frequency != null)
            {
                _context.Frequencies.Remove(frequency);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool FrequencyExists(int id)
        {
          return (_context.Frequencies?.Any(e => e.Id == id)).GetValueOrDefault();
        }

        private async Task<List<Frequency>> FrequenciesList() {

            if (_context.Frequencies == null)
            {
                return null;
            }
            if (_context.Spots == null)
            {
                return null;
            }
            var spot = await _context.Spots.ToListAsync();      //Para ser usado na conversão de Frel para Umid%
            var frequency = await _context.Frequencies
                .ToListAsync();

            if (frequency == null)
            {
                return null;
            }
            if (spot == null)
            {
                return null;
            }
            ///<summary>
            ///
            /// Convert frequencies into percent of soil moisture
            /// 
            /// </summary>
            foreach (Frequency item in frequency)
            {

                foreach (Spot sitem in spot.Where(s => s.Sensor_Id == item.Sensor_Id).Where(t => t.Name == "Frl3"))
                {
                    item.Frl3 = (item.Frl3 * sitem.A) + sitem.B;
                }

                foreach (Spot sitem in spot.Where(s => s.Sensor_Id == item.Sensor_Id).Where(t => t.Name == "Frl2"))
                {
                    item.Frl2 = (item.Frl2 * sitem.A) + sitem.B;
                }

                foreach (Spot sitem in spot.Where(s => s.Sensor_Id == item.Sensor_Id).Where(t => t.Name == "Frl1"))
                {
                    item.Frl1 = (item.Frl1 * sitem.A) + sitem.B;
                }


            }

            return frequency;


        }

    }
}

SensorData/Views/Frequencies/Index.cshtml
@model IEnumerable<SensorData.Models.Frequency>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";

    DateTime PegaHoraBrasilia() => TimeZoneInfo.ConvertTime(DateTime.Now, TimeZoneInfo.FindSystemTimeZoneById("E. South America Standard Time"));
    //var dateTimeNow = PegaHoraBrasilia().ToLocalTime();

    var labelsModel = "";
    float frl1Model;
    float frl2Model;
    float frl3Model;
    String[]? labelsArray = new String[550];
    float[]? frl1Array = new float[550];
    float[]? frl2Array = new float[550];
    float[]? frl3Array = new float[550];

    float[]? frl1ArrayAvg = new float[550];
    float[]? frl2ArrayAvg = new float[550];
    float[]? frl3ArrayAvg = new float[550];

    float A;
    float B;

    int sensorSpot = 2;
    var index = 0;


    float[] avgFrl1 = new float[10];
    float[] avgFrl2 = new float[10];
    float[] avgFrl3 = new float[10];

    var indexT = 0;

    Frequency[] itemT = new Frequency[550];


    Frequency[] tempItem10 = new Frequency[10];
    Frequency[] tempItemArr = new Frequency[550];

    Frequency[] tempItemArrT = new Frequency[550];

    List<Frequency> freqList = new List<Frequency>();

    var initialHour = 0;
    var initialMinute = 0;


}


<h2>24 horas de leituras de dados</h2>

<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h2 class="h2">Umidade de solo do sensor (%): SS</h2>
    <div class="btn-toolbar mb-2 mb-md-0">
        <a class="nav-link" asp-area="" asp-controller="Frequencies1" asp-action="Index">Bananas</a>
    </div>
    <div class="btn-toolbar mb-2 mb-md-0">
        <div class="btn-group me-2">
            <button type="button" class="btn btn-sm btn-outline-secondary">Compartilhar</button>
            <button type="button" class="btn btn-sm btn-outline-secondary">Exportar</button>
        </div>
        <button type="button" class="btn btn-sm btn-outline-secondary dropdown-toggle">
            <span data-feather="calendar" class="align-text-bottom"></span>
            Semana
        </button>
    </div>
</div>

<canvas class="my-4 w-100" id="lineChart" width="900" height="380"></canvas>
<div>
    <div class="btn-toolbar mb-2 mb-md-0">
        <a class="nav-link" asp-area="" asp-controller="Frequencies" asp-action="ViewTable">Tabela</a>
    </div>

</div>

<script src="../lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>

<script src="https://cdn.jsdelivr.net/npm/feather-icons@4.28.0/dist/feather.min.js" integrity="sha384-uO3SXW5IuS1ZpFPKugNNWqTZRRglnUJK6UAZ/gxOX80nxEkN9NcGZTftn6RzhGWE" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.4/dist/Chart.min.js" integrity="sha384-zNy6FEbO50N+Cg5wap8IKA4M/ZnLJgzc6w2NqACZaK0u0FXfOWRRJOnQtpZun8ha" crossorigin="anonymous"></script>

<script src="../lib/bootstrap/dist/css/dashboard.css"></script>
<script src="../lib/bootstrap/dist/css/dashboard.rtl.css"></script>



<script>
    // Graphs
    const ctxA = document.getElementById('lineChart');
    


    createGraphic(ctxA);
    function createGraphic(ctx) {



    @foreach (var item in Model.Where(t => t.ReadDateTime >= PegaHoraBrasilia().AddHours(-28)).Where(t => t.Sensor_Id == sensorSpot).ToList())
        {
            //item.ReadDateTime.AddHours(3);                            //Time correction adding 3 hours
            labelsModel = item.ReadDateTime.AddHours(3).ToString("dd/MM/yyyy HH:mm");     //Time correction adding 3 hours
            frl1Model = item.Frl1;
            frl2Model = item.Frl2;
            frl3Model = item.Frl3;

            labelsArray[index] = labelsModel;
            frl1Array[index] = frl1Model;
            frl2Array[index] = frl2Model;
            frl3Array[index] = frl3Model;
            tempItemArr[index] = item;

            tempItemArrT = tempItemArr;


            index++;
            if (index >= labelsArray.Length)
            {
                break;
            }
        }
    ;


        //// Graphs
        //const ctx = document.getElementById('lineChart');
        // eslint-disable-next-line no-unused-vars
        const myChart = new Chart(ctx, {
            type: 'line',
            data: {
                labels: [],
                datasets: [{
                    label: "SS: 0-20",
                    data: [],
                    lineTension: 0,
                    backgroundColor: 'transparent',
                    borderColor: '#008bff',
                    borderWidth: 4,
                    pointBackgroundColor: '#008bff'
                },
                {
                    label: "SS: 20-40",
                    data: [],
                    lineTension: 0,
                    backgroundColor: 'transparent',
                    borderColor: '#ff8b00',
                    borderWidth: 4,
                    pointBackgroundColor: '#ff8b00'
                },
                {
                    label: "SS: 40-60",
                    data: [],
                    lineTension: 0,
                    backgroundColor: 'transparent',
                    borderColor: '#00ff8b',
                    borderWidth: 4,
                    pointBackgroundColor: '#00ff8b'
                },
                {
                    label: "Capacidade de campo SS: 0-20 = 15.181",
                    data: [],
                    lineTension: 0,
                    backgroundColor: 'transparent',
                    borderColor: '#008bff',
                    borderWidth: 1,
                    pointBackgroundColor: '#008bff'
                },
                {
                    label: "Capacidade de campo SS: 20-40 = 9.325",
                    data: [],
                    lineTension: 0,
                    backgroundColor: 'transparent',
                    borderColor: '#ff8b00',
                    borderWidth: 1,
                    pointBackgroundColor: '#ff8b00'
                },
                {
                    label: "Capacidade de campo SS: 40-60 = 10.153",
                    data: [],
                    lineTension: 0,
                    backgroundColor: 'transparent',
                    borderColor: '#00ff8b',
                    borderWidth: 1,
                    pointBackgroundColor: '#00ff8b'
                }
                ]
            },
            options: {
                scales: {
                    yAxes: [{
                        ticks: {
                            beginAtZero: false
                        }
                    }]
                },
                legend: {
                    display: true
                }
            }
        });
        var dtLabels = new Array();         //Array Javascript
        var dtFrl1 = new Array();
        var dtFrl2 = new Array();
        var dtFrl3 = new Array();
        var indexJS = 0;
        var fieldCap20 = 15.181;
        var fieldCap40 = 9.325;
        var fieldCap60 = 10.153;


        @for (var i = 0; i < labelsArray.Length; i++)
        {
            if(tempItemArr[i] == null)
            {
                break;
            }

            initialHour = tempItemArr[i].ReadDateTime.Hour;
            initialMinute = tempItemArr[i].ReadDateTime.Minute;

            if (i + 1 >= 550)
                break;

            if (tempItemArr[i + 1] == null)
            {
            
                @:(dtLabels[indexJS] = '@labelsArray[i]');
                @:(dtFrl1[indexJS] = '@frl1Array[i]'.replace(',', '.'));
                @:(dtFrl2[indexJS] = '@frl2Array[i]'.replace(',', '.'));
                @:(dtFrl3[indexJS] = '@frl3Array[i]'.replace(',', '.'));

                break;
            }
            else{
                if (tempItemArr[i + 1].ReadDateTime.Hour <= initialHour)
                {
                    if (tempItemArr[i + 1].ReadDateTime.Minute < initialMinute + 3)
                    {
                        continue;
                    }
                }

            }

            if (i >= 550)
                        break;

            indexT++;


            @:(dtLabels[indexJS] = '@labelsArray[i]');
            @:(dtFrl1[indexJS] = '@frl1Array[i]'.replace(',', '.'));
            @:(dtFrl2[indexJS] = '@frl2Array[i]'.replace(',', '.'));
            @:(dtFrl3[indexJS] = '@frl3Array[i]'.replace(',', '.'));

            @:(indexJS++);

        
        }


            for (let i = 0; i <= dtLabels.length; i++) {
                if (dtLabels[i] == null)
                    break;

                    myChart.data.labels[i] = dtLabels[i];
                    myChart.data.datasets[0].data[i] = dtFrl1[i];
                    myChart.data.datasets[1].data[i] = dtFrl2[i];
                    myChart.data.datasets[2].data[i] = dtFrl3[i];
                    //myChart.data.datasets[3].data[i] = fieldCap20;
                    //myChart.data.datasets[4].data[i] = fieldCap40;
                    //myChart.data.datasets[5].data[i] = fieldCap60;

            }
        myChart.update();
    }



</script>

SensorData/Views/Frequencies/Index1.cshtml
@model IEnumerable<SensorData.Models.Frequency>

@{
    ViewData["Title"] = "Index1";
    Layout = "~/Views/Shared/_Layout.cshtml";

    DateTime PegaHoraBrasilia() => TimeZoneInfo.ConvertTime(DateTime.Now, TimeZoneInfo.FindSystemTimeZoneById("E. South America Standard Time"));
    var dateTimeNow = PegaHoraBrasilia().ToLocalTime();

    var labelsModel = "";
    float frl1Model;
    float frl2Model;
    float frl3Model;
    String[]? labelsArray = new String[20];
    float[]? frl1Array = new float[20];
    float[]? frl2Array = new float[20];
    float[]? frl3Array = new float[20];

    int sensorSpot = 3;

    var index = 0;

}


<h2>12 horas de leituras de dados</h2>

<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h2 class="h2">Umidade de solo em %</h2>

@*    <div>
        <select id="local_sensor" onchange="changePage()">
            <option value="2">SS</option>
            <option value="3">Banana</option>
        </select>
    </div>*@

    <div class="btn-toolbar mb-2 mb-md-0">
        <div class="btn-group me-2">
            <button type="button" class="btn btn-sm btn-outline-secondary">Compartilhar</button>
            <button type="button" class="btn btn-sm btn-outline-secondary">Exportar</button>
        </div>
        <button type="button" class="btn btn-sm btn-outline-secondary dropdown-toggle">
            <span data-feather="calendar" class="align-text-bottom"></span>
            Semana
        </button>
    </div>
</div>

<canvas class="my-4 w-100" id="lineChart" width="900" height="380"></canvas>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Sensor_Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Frl1)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Frl2)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Frl3)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ReadDateTime)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Where(t => t.ReadDateTime >= dateTimeNow.AddHours(-56)).Where(t => t.Sensor_Id == sensorSpot).ToList())
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Sensor_Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Frl1)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Frl2)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Frl3)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ReadDateTime)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>




<script src="../lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>

<script src="https://cdn.jsdelivr.net/npm/feather-icons@4.28.0/dist/feather.min.js" integrity="sha384-uO3SXW5IuS1ZpFPKugNNWqTZRRglnUJK6UAZ/gxOX80nxEkN9NcGZTftn6RzhGWE" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.4/dist/Chart.min.js" integrity="sha384-zNy6FEbO50N+Cg5wap8IKA4M/ZnLJgzc6w2NqACZaK0u0FXfOWRRJOnQtpZun8ha" crossorigin="anonymous"></script>

<script src="../lib/bootstrap/dist/css/dashboard.css"></script>
<script src="../lib/bootstrap/dist/css/dashboard.rtl.css"></script>
@*<script src="../lib/bootstrap/dist/js/dashboard.js"></script>*@


<script>

    console.log("Teste de console no javascript");

    // Graphs
    const ctx = document.getElementById('lineChart');


    //// Graphs
    //const ctx = document.getElementById('lineChart');
    // eslint-disable-next-line no-unused-vars
    const myChart = new Chart(ctx, {
        type: 'line',
        data: {
            labels: [],
            datasets: [{
                label: "Frl1",
                data: [],
                lineTension: 0,
                backgroundColor: 'transparent',
                borderColor: '#007bff',
                borderWidth: 4,
                pointBackgroundColor: '#008bff'
            },
            {
                label: "Frl2",
                data: [],
                lineTension: 0,
                backgroundColor: 'transparent',
                borderColor: '#ff8b00',
                borderWidth: 4,
                pointBackgroundColor: '#ff8b00'
            },
            {
                label: "Frl3",
                data: [],
                lineTension: 0,
                backgroundColor: 'transparent',
                borderColor: '#00ff8b',
                borderWidth: 4,
                pointBackgroundColor: '#00ff8b'
            },
            ]
        },
        options: {
            scales: {
                yAxes: [{
                    ticks: {
                        beginAtZero: false
                    }
                }]
            },
            legend: {
                display: false
            }
        }
    });


    updateGraphic();

    function updateGraphic() {


    @foreach (var item in Model.Where(t => t.ReadDateTime >= dateTimeNow.AddHours(-56)).Where(t => t.Sensor_Id == sensorSpot).ToList())
    {
        Console.Write(item.Sensor_Id.ToString() + " " + item.Frl1 + " " + item.Frl2 + " " + item.Frl3 + " ");

        labelsModel = item.ReadDateTime.ToString();
        frl1Model = item.Frl1;
        frl2Model = item.Frl2;
        frl3Model = item.Frl3;

        labelsArray[index] = labelsModel;
        frl1Array[index] = frl1Model;
        frl2Array[index] = frl2Model;
        frl3Array[index] = frl3Model;

        index++;
    };

 
        var dtLabels = new Array();         //Array Javascript
        var dtFrl1 = new Array();
        var dtFrl2 = new Array();
        var dtFrl3 = new Array();

        var indexJS = 0;

    @for (var i = 0; i < labelsArray.Length; i++)
    {
        @:(dtLabels[indexJS] = '@labelsArray[i]');
        @:(dtFrl1[indexJS] = '@frl1Array[i]'.replace(',', '.'));
        @:(dtFrl2[indexJS] = '@frl2Array[i]'.replace(',', '.'));
        @:(dtFrl3[indexJS] = '@frl3Array[i]'.replace(',', '.'));
        @:(indexJS++);
    }


        for (let i = 0; i < dtLabels.length; i++) {

            if (dtLabels[i] == 0)
                break;

            myChart.data.labels[i] = dtLabels[i];
            myChart.data.datasets[0].data[i] = dtFrl1[i];
            myChart.data.datasets[1].data[i] = dtFrl2[i];
            myChart.data.datasets[2].data[i] = dtFrl3[i];

        }

        myChart.update();

    }
    function changePage() {
        var valueR = document.getElementById('local_sensor').value;
        if (valueR == '3'){
            @{<a asp-controller="SensorData" asp-action="Index1">Bananas</a>}
        }
        else{
            @{<a asp-controller="SensorData" asp-action="Index">SS</a>}
        }
        
    }

</script>