SensorData/Controllers/FrequenciesController.cs
/// <summary>
/// 
/// This code is to manipulate the Frequencies model from SS End Device to be presented as moisture on Views
/// 
/// Author: Alexandre Cavalcanti
/// Date: 05/31/2023
/// 
/// </summary>

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using NuGet.Protocol;
using SensorData.Models;


namespace SensorData.Controllers
{
    public class FrequenciesController : Controller
    {
        private readonly SensorContext _context;

        public FrequenciesController(SensorContext context)
        {
            _context = context;
        }

        // GET: Frequencies
        public async Task<IActionResult> Index()
        {
            return View(await FrequenciesList());
        }

        //GET: Frequencies/ViewTable

        public async Task<IActionResult> ViewTable()
        {

            var frequencies = await FrequenciesList();


            return View(frequencies);
        }


        // GET: Frequencies/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Frequencies == null)
            {
                return NotFound();
            }

            var frequency = await _context.Frequencies
                .FirstOrDefaultAsync(m => m.Id == id);
            if (frequency == null)
            {
                return NotFound();
            }

            return View(frequency);
        }

        // GET: Frequencies/Create
        public IActionResult Create()
        {
            return View();
        }

        //POST: Frequencies/Create
        //To protect from overposting attacks, enable the specific properties you want to bind to.
        //For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Sensor_Id,Frl1,Frl2,Frl3,ReadDateTime")] Frequency frequency)
        {
            if (ModelState.IsValid)
            {
                _context.Add(frequency);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(frequency);
        }


        // GET: Frequencies/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Frequencies == null)
            {
                return NotFound();
            }

            var frequency = await _context.Frequencies.FindAsync(id);
            if (frequency == null)
            {
                return NotFound();
            }
            return View(frequency);
        }

        // POST: Frequencies/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Sensor_Id,Frl1,Frl2,Frl3,ReadDateTime")] Frequency frequency)
        {
            if (id != frequency.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(frequency);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FrequencyExists(frequency.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(frequency);
        }

        // GET: Frequencies/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Frequencies == null)
            {
                return NotFound();
            }

            var frequency = await _context.Frequencies
                .FirstOrDefaultAsync(m => m.Id == id);
            if (frequency == null)
            {
                return NotFound();
            }

            return View(frequency);
        }

        // POST: Frequencies/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Frequencies == null)
            {
                return Problem("Entity set 'SensorContext.Frequencies'  is null.");
            }
            var frequency = await _context.Frequencies.FindAsync(id);
            if (frequency != null)
            {
                _context.Frequencies.Remove(frequency);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool FrequencyExists(int id)
        {
          return (_context.Frequencies?.Any(e => e.Id == id)).GetValueOrDefault();
        }

        private async Task<List<Frequency>> FrequenciesList() {

            if (_context.Frequencies == null)
            {
                return null;
            }
            if (_context.Spots == null)
            {
                return null;
            }
            var spot = await _context.Spots.ToListAsync();      //Para ser usado na conversão de Frel para Umid%
            var frequency = await _context.Frequencies
                .ToListAsync();

            if (frequency == null)
            {
                return null;
            }
            if (spot == null)
            {
                return null;
            }
            ///<summary>
            ///
            /// Convert frequencies into percent of soil moisture
            /// 
            /// </summary>
            foreach (Frequency item in frequency)
            {

                foreach (Spot sitem in spot.Where(s => s.Sensor_Id == item.Sensor_Id).Where(t => t.Name == "Frl3"))
                {
                    item.Frl3 = (item.Frl3 * sitem.A) + sitem.B;
                }

                foreach (Spot sitem in spot.Where(s => s.Sensor_Id == item.Sensor_Id).Where(t => t.Name == "Frl2"))
                {
                    item.Frl2 = (item.Frl2 * sitem.A) + sitem.B;
                }

                foreach (Spot sitem in spot.Where(s => s.Sensor_Id == item.Sensor_Id).Where(t => t.Name == "Frl1"))
                {
                    item.Frl1 = (item.Frl1 * sitem.A) + sitem.B;
                }


            }

            return frequency;


        }

    }
}

SensorData/Controllers/SensorsController.cs
/// <summary>
/// 
/// This code is to manipulate the Sensors model to be presented on Views
/// 
/// Author: Alexandre Cavalcanti
/// Date: 05/31/2023
/// 
/// </summary>

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SensorData.Models;

namespace SensorData.Controllers
{
    public class SensorsController : Controller
    {
        private readonly SensorContext _context;

        public SensorsController(SensorContext context)
        {
            _context = context;
        }

        // GET: Sensors
        public async Task<IActionResult> Index()
        {
              return _context.Sensors != null ? 
                          View(await _context.Sensors.ToListAsync()) :
                          Problem("Entity set 'SensorContext.Sensors'  is null.");
        }

        // GET: Sensors/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Sensors == null)
            {
                return NotFound();
            }

            var sensor = await _context.Sensors
                .FirstOrDefaultAsync(m => m.Id == id);
            if (sensor == null)
            {
                return NotFound();
            }

            return View(sensor);
        }

        // GET: Sensors/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Sensors/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Ar1,Ar2,Ar3,H2o1,H2o2,H2o3,CalDateTime")] Sensor sensor)
        //public async Task<IActionResult> Create([FromQuery] Sensor sensor)
        {
            if (ModelState.IsValid)
            {
                _context.Add(sensor);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(sensor);
        }

        // GET: Sensors/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Sensors == null)
            {
                return NotFound();
            }

            var sensor = await _context.Sensors.FindAsync(id);
            if (sensor == null)
            {
                return NotFound();
            }
            return View(sensor);
        }

        // POST: Sensors/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Ar1,Ar2,Ar3,H2o1,H2o2,H2o3,CalDateTime")] Sensor sensor)
        {
            if (id != sensor.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(sensor);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SensorExists(sensor.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(sensor);
        }

        // GET: Sensors/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Sensors == null)
            {
                return NotFound();
            }

            var sensor = await _context.Sensors
                .FirstOrDefaultAsync(m => m.Id == id);
            if (sensor == null)
            {
                return NotFound();
            }

            return View(sensor);
        }

        // POST: Sensors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Sensors == null)
            {
                return Problem("Entity set 'SensorContext.Sensors'  is null.");
            }
            var sensor = await _context.Sensors.FindAsync(id);
            if (sensor != null)
            {
                _context.Sensors.Remove(sensor);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SensorExists(int id)
        {
          return (_context.Sensors?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

SensorData/Controllers/SpotsController.cs
/// <summary>
/// 
/// This code is to manipulate the Spots model to be presented on Views
/// 
/// Author: Alexandre Cavalcanti
/// Date: 05/31/2023
/// 
/// </summary>

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SensorData.Models;

namespace SensorData.Controllers
{
    public class SpotsController : Controller
    {
        private readonly SensorContext _context;

        public SpotsController(SensorContext context)
        {
            _context = context;
        }

        // GET: Spots
        public async Task<IActionResult> Index()
        {
              return _context.Spots != null ? 
                          View(await _context.Spots.ToListAsync()) :
                          Problem("Entity set 'SensorContext.Spots'  is null.");
        }

        // GET: Spots/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Spots == null)
            {
                return NotFound();
            }

            var spot = await _context.Spots
                .FirstOrDefaultAsync(m => m.Id == id);
            if (spot == null)
            {
                return NotFound();
            }

            return View(spot);
        }

        // GET: Spots/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Spots/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult<SpotDTO>> Create([Bind("Id,Name,Lat,Long,A,B,R2,Sensor_Id")] SpotDTO spotDTO)
        {
            if (ModelState.IsValid)
            {
                var spot = new Spot()
                {
                    Name = spotDTO.Name,
                    Lat = spotDTO.Lat,
                    Long = spotDTO.Long,
                    A = spotDTO.A,
                    B = spotDTO.B,
                    R2 = spotDTO.R2,
                    Sensor_Id = spotDTO.Sensor_Id
                };
                _context.Add(spot);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(spotDTO);
        }

        // GET: Spots/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Spots == null)
            {
                return NotFound();
            }

            var spot = await _context.Spots.FindAsync(id);
            if (spot == null)
            {
                return NotFound();
            }
            return View(spot);
        }

        // POST: Spots/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Lat,Long,A,B,R2,Sensor_Id")] Spot spot)
        {
            if (id != spot.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(spot);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SpotExists(spot.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(spot);
        }

        // GET: Spots/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Spots == null)
            {
                return NotFound();
            }

            var spot = await _context.Spots
                .FirstOrDefaultAsync(m => m.Id == id);
            if (spot == null)
            {
                return NotFound();
            }

            return View(spot);
        }

        // POST: Spots/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Spots == null)
            {
                return Problem("Entity set 'SensorContext.Spots'  is null.");
            }
            var spot = await _context.Spots.FindAsync(id);
            if (spot != null)
            {
                _context.Spots.Remove(spot);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SpotExists(int id)
        {
          return (_context.Spots?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

SensorData/Views/Home/Index.cshtml
@model IEnumerable<SensorData.Models.Frequency>


@{
    ViewData["Title"] = "Bluewater";
    DateTime PegaHoraBrasilia() => TimeZoneInfo.ConvertTime(DateTime.Now, TimeZoneInfo.FindSystemTimeZoneById("E. South America Standard Time"));
    var dateTimeNow = PegaHoraBrasilia();


}

    <div class="row">
        <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
            <div class="position-sticky pt-3 sidebar-sticky">
                <ul class="nav flex-column">
                    <li class="nav-item">
                    <a class="nav-link active" aria-current="page" asp-area="" asp-controller="Frequencies" asp-action="Index">
                            <span data-feather="home" class="align-text-bottom"></span>
                            Sensor SS
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Frequencies1" asp-action="Index">
                            <span data-feather="users" class="align-text-bottom"></span>
                            Sensor Bananas
                        </a>
                    </li
                <li class="nav-item">
                    <a class="nav-link" asp-area="" asp-controller="Frequencies2" asp-action="Index">
                        <span data-feather="users" class="align-text-bottom"></span>
                        Sensor de Teste
                    </a>
                </li>
                    <li class="nav-item">
                    <a class="nav-link" asp-area="" asp-controller="Sensors" asp-action="Index">
                            <span data-feather="file" class="align-text-bottom"></span>
                            Calibrações
                        </a>
                    </li>
                    <li class="nav-item">
                    <a class="nav-link" asp-area="" asp-controller="Spots" asp-action="Index">
                            <span data-feather="shopping-cart" class="align-text-bottom"></span>
                            Locais de instalação
                        </a>
                    </li>
                    <li class="nav-item">
                    <a class="nav-link" href="#">
                            <span data-feather="bar-chart-2" class="align-text-bottom"></span>
                            Relatórios
                        </a>
                    </li>
                    <li class="nav-item">
                    <a class="nav-link" href="#">
                            <span data-feather="layers" class="align-text-bottom"></span>
                            Mapas
                        </a>
                    </li>
                </ul>

                <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted text-uppercase">
                    <span>Históricos de relatórios</span>
                    <a class="link-secondary" href="#" aria-label="Add a new report">
                        <span data-feather="plus-circle" class="align-text-bottom"></span>
                    </a>
                </h6>
                <ul class="nav flex-column mb-2">
                    <li class="nav-item">
                        <a class="nav-link" href="#">
                            <span data-feather="file-text" class="align-text-bottom"></span>
                            Mês corrente
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">
                            <span data-feather="file-text" class="align-text-bottom"></span>
                            Último trimestre
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">
                            <span data-feather="file-text" class="align-text-bottom"></span>
                            Último ano
                        </a>
                    </li>
                </ul>
            </div>
        </nav>

        <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">

        <img src="../images/fotos.jpg" sizes="(max-width: 800px) 300px, 50vw" />

        </main>
    </div>